### ISSUE TITLE
Tap event fires together with doubletap event

### ISSUE THREAD

**Issue by yairEO** [ngryman/jquery.finger#22]
This should never ever happen. only one event at a time. most people put 2 different events on an object, and the UX will get crazy when the user double tap to do one action and the single-tap event also gets fired and does the second thing, which wasn't intended to happen at all.

**Comment by tlhunter** [comment]
What would be awesome is if Finger knows that BOTH tap and doubletap are being listened for on an element, it retains the 300ms delay, but when ONLY tap is being used, skip the 300ms delay.

**Comment by ngryman** [comment]
@tlhunter This is a edge case involving too much code, without mentioning that some user may want another behaviour.
In this kind of scenario, I would advice to handle this yourself as you have all you need to do so.
