### ISSUE TITLE
Calling a function once drag event over?

### ISSUE THREAD

**Issue by majimekun** [ngryman/jquery.finger#33]
Hi Nicolas,
I would like to know if there is a way to call a function when the drag/flick event is over.
Since I couldn't find it in the documentation I guess it's not possible yet ... but could you confirm?
I've also tried with touchend but with no success.
Cheers

**Comment by ngryman** [comment]
Hey,

Yes you can do it by checking the `end` property of the `event`.
I think I forgot to mention this in the docs. I will add it :)
