### ISSUE TITLE
Desktop browser issues

### ISSUE THREAD

**Issue by dev4press** [ngryman/jquery.finger#41]
I tested the script on the Windows 10 laptop with touch screen, and in different browsers it behaves differently:

* Chrome and Opera: Drag and Flick don't work at all.
* Edge (Internet Explorer replacement): Drag and Flick always fired together. Double tab not working, browser zooms the page.
* Firefox: Flick not working.

Milan

**Comment by ngryman** [comment]
Hi, sorry for the late, could you provide a **jsfiddle** illustrating the bugs? Thanks!

**Comment by sk-blog** [comment]
Firefox 44.0.2 ： Tap not working

Reason :

`hasTouch = 'ontouchstart' in window && !(isChrome && !isAndroid)`

**Comment by ngryman** [comment]
All tests are passing in **Firefox 49**. As mentioned earlier in this issue, I need a **jsfiddle** illustrating the issue. I can't treat a bug seriously without a clear report. Thanks.
