### ISSUE TITLE
possibly incorrect sem-ver in bower.json

### ISSUE THREAD

**Issue by xstherrera1987** [ngryman/jquery.finger#45]
bower.json specifies the jquery dependency as `"jquery": "~1.7.0"` which i believe means `>= 1.7.0 && < 1.8`.  I don't know whether this is accurate but I think you may have meant simply `>1.7.0`.  I noticed while installing via bower where it tries to resolve the dependency with jquery 1.7.2.

command and output:

    $ bower install --save jquery.finger
    bower jquery.finger#*       not-cached git://github.com/ngryman/jquery.finger.git#*
    bower jquery.finger#*          resolve git://github.com/ngryman/jquery.finger.git#*
    bower jquery.finger#*         download     https://github.com/ngryman/jquery.finger/archive/v0.1.3.tar.gz
    bower jquery.finger#*          extract archive.tar.gz
    bower jquery.finger#*         mismatch Version declared in the json (0.1.2) is different than the resolved one (0.1.3)
    bower jquery.finger#*         resolved git://github.com/ngryman/jquery.finger.git#0.1.3
    bower jquery#~1.7.0         not-cached git://github.com/jquery/jquery.git#~1.7.0
    bower jquery#~1.7.0            resolve git://github.com/jquery/jquery.git#~1.7.0
    bower jquery#~1.7.0           download https://github.com/jquery/jquery/archive/1.7.2.tar.gz
    bower jquery#~1.7.0            extract archive.tar.gz
    bower jquery#~1.7.0       invalid-meta jquery is missing "ignore" entry in bower.json
    bower jquery#~1.7.0           resolved git://github.com/jquery/jquery.git#1.7.2
    bower jquery#~2.1.4             cached git://github.com/jquery/jquery.git#2.1.4
    bower jquery#~2.1.4           validate 2.1.4 against git://github.com/jquery/jquery.git#~2.1.4

    Unable to find a suitable version for jquery, please choose one:
        1) jquery#~1.7.0 which resolved to 1.7.2 and is required by jquery.finger#0.1.3
        2) jquery#>1.8.* which resolved to 2.1.4 and is required by jquery-ujs#1.1.0
        3) jquery#~2.1.4 which resolved to 2.1.4 and is required by <my-app-name>

    Prefix the choice with ! to persist it to bower.json

    ? Answer

**Comment by ngryman** [comment]
Oh nice catch!
