### ISSUE TITLE
Right click fires tap event

### ISSUE THREAD

**Issue by CedricReichenbach** [ngryman/jquery.finger#46]
This is especially a problem while developing and using it on desktop: One might right click an element for inspection, and an unintended action is executed.

**Comment by ngryman** [comment]
Yes you totally right. I'll look into it `asap`.

**Comment by giulianoriccio** [comment]
adding this right at the begin of startHandler fixed it for me (event.which should always be 0 for touch events while for mouse events: 1 = left, 2 = middle, 3 = right):

```
    if (event.which > 1) {
      return;
    }
```

**Comment by ngryman** [comment]
Merged and released as `0.1.5`. Thanks!
