### ISSUE TITLE
Drag gets triggered on mouse/tap up

### ISSUE THREAD

**Issue by ixley** [ngryman/jquery.finger#49]
**Expected behavior**
Long press (or sustained click) with no x/y movement triggers `press` event, but not `drag`.

**Actual behavior**
A long press (or sustained click) triggers the `drag` event on mouse up or touch end.

**Comment by ngryman** [comment]
Hey @ixley,

Thanks for the report! May I ask you to link me a [JSFiddle](https://jsfiddle.net/) that reproduces the issue? That would help me to quickly review the bug.

Thanks!

**Comment by ixley** [comment]
@ngryman I actually noticed this exhibited on the demo site – (Mac) Safari, Chrome, and Firefox (latest versions)

**Comment by ngryman** [comment]
Thanks for the catch 🐞. I'm on it.

**Comment by ngryman** [comment]
Fixed and released as `0.1.6`. Thanks!
